---
clone:
  depth: 1
kind: pipeline
name: Tempest Drone
steps:
  -
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Syu --noconfirm --needed git bc inetutils zip libxml2 python3 jre-openjdk jdk-openjdk flex bison libc++ python-pip
      - cd /drone/src
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/KazuDante89/arrow_lavender_kernel/Pelt-Lab_v0.2/build.sh | bash"
    environment:
      TOKEN:
        from_secret: token
    image: archlinux:base-devel
    trigger:
      branch:
        - Pelt-Lab_v0.2
