---
clone:
  depth: 1
kind: pipeline
name: Work
steps:
  -
    commands:
      - "export token=$TOKEN"
      - "curl https://raw.githubusercontent.com/KazuDante89/arrow_lavender_kernel/Pelt_Lab3/build.sh | bash"
    environment:
      TOKEN:
        from_secret: token
    image: fadlyas/kernel_dockerfile
    name: KazuDante
    trigger:
      branch:
        - Pelt_Lab3
