/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

#ifdef CONFIG_PELT_UTIL_HALFLIFE_32
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xfa83b2da,0xf5257d14,0xefe4b99a,
        0xeac0c6e6,0xe5b906e6,0xe0ccdeeb,0xdbfbb796,
        0xd744fcc9,0xd2a81d91,0xce248c14,0xc9b9bd85,
        0xc5672a10,0xc12c4cc9,0xbd08a39e,0xb8fbaf46,
        0xb504f333,0xb123f581,0xad583ee9,0xa9a15ab4,
        0xa5fed6a9,0xa2704302,0x9ef5325f,0x9b8d39b9,
        0x9837f050,0x94f4efa8,0x91c3d373,0x8ea4398a,
        0x8b95c1e3,0x88980e80,0x85aac367,0x82cd8698,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1002, 1982, 2941, 3880, 4798, 5697, 6576, 7437, 8279, 9103,
         9909,10698,11470,12226,12966,13690,14398,15091,15769,16433,17082,
        17718,18340,18949,19545,20128,20698,21256,21802,22336,22859,23371,
};

#define LOAD_AVG_PERIOD 32
#define LOAD_AVG_MAX 47742
#define LOAD_AVG_MAX_N 345

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_30
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xfa2727da,0xf4707fd4,0xeedb4007,
        0xe966a51e,0xe411f039,0xdedc66d6,0xd9c552b3,
        0xd4cc01ba,0xcfefc5e5,0xcb2ff529,0xc68be95a,
        0xc203001c,0xbd949ac5,0xb9401e4c,0xb504f333,
        0xb0e28570,0xacd8445b,0xa8e5a29d,0xa50a1614,
        0xa14517cb,0x9d9623df,0x99fcb970,0x96785a91,
        0x93088c35,0x8facd61d,0x8c64c2cc,0x892fdf70,
        0x860dbbda,0x82fdea6a,
};

static const u32 runnable_avg_yN_sum[] = {
            0, 1000, 1977, 2932, 3865, 4777, 5668, 6539, 7390, 8221, 9033,
         9827,10603,11361,12102,12826,13533,14224,14899,15559,16204,16834,
        17450,18052,18640,19214,19775,20323,20859,21383,21895,
};

#define LOAD_AVG_PERIOD 30
#define LOAD_AVG_MAX 44790
#define LOAD_AVG_MAX_N 323

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_28
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf9bd8e48,0xf3a24b24,0xedad4152,
        0xe7dd818c,0xe2322269,0xdcaa4034,0xd744fcc9,
        0xd2017f74,0xccdef4cc,0xc7dc8e94,0xc2f98399,
        0xbe350f94,0xb98e730b,0xb504f333,0xb097d9d0,
        0xac46751e,0xa81017af,0xa3f41854,0x9ff1d200,
        0x9c08a3b0,0x9837f050,0x947f1ea5,0x90dd9931,
        0x8d52ce1f,0x89de2f2b,0x867f318b,0x83354dd8,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  998, 1972, 2922, 3849, 4753, 5635, 6496, 7336, 8155, 8954,
         9734,10494,11236,11960,12666,13355,14027,14682,15321,15945,16554,
        17148,17727,18292,18843,19381,19906,20418,
};

#define LOAD_AVG_PERIOD 28
#define LOAD_AVG_MAX 41839
#define LOAD_AVG_MAX_N 302

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_26
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf943ed16,0xf2b5353d,0xec52a6fd,
        0xe61b18ec,0xe00d6972,0xda287e94,0xd46b45c2,
        0xced4b3a8,0xc963c3f8,0xc417793c,0xbeeedcac,
        0xb9e8fdfc,0xb504f333,0xb041d87e,0xab9ed00c,
        0xa71b01de,0xa2b59ba6,0x9e6dd09d,0x9a42d961,
        0x9633f3cc,0x924062d7,0x8e676e70,0x8aa86360,
        0x87029325,0x837553d5,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  997, 1967, 2912, 3832, 4728, 5600, 6449, 7276, 8081, 8865,
         9628,10371,11095,11800,12486,13154,13805,14438,15055,15656,16241,
        16810,17364,17904,18430,18942,
};

#define LOAD_AVG_PERIOD 26
#define LOAD_AVG_MAX 38887
#define LOAD_AVG_MAX_N 280

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_24
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf8b65139,0xf1a1bf37,0xeac0c6e6,
        0xe411f039,0xdd93cdd6,0xd744fcc9,0xd124243d,
        0xcb2ff529,0xc5672a10,0xbfc886ba,0xba52d7ee,
        0xb504f333,0xafddb68e,0xaadc0846,0xa5fed6a9,
        0xa14517cb,0x9cadc957,0x9837f050,0x93e298df,
        0x8facd61d,0x8b95c1e3,0x879c7c96,0x83c02cf9,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  994, 1960, 2899, 3811, 4697, 5558, 6394, 7206, 7995, 8762,
         9507,10231,10934,11617,12281,12926,13552,14161,14752,15326,15884,
        16426,16953,17465,
};

#define LOAD_AVG_PERIOD 24
#define LOAD_AVG_MAX 35936
#define LOAD_AVG_MAX_N 259

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_22
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf80f5dd0,0xf05dc6b1,0xe8e94611,
        0xe1aff6e7,0xdab00335,0xd3e7a391,0xcd551eb0,
        0xc6f6c8f7,0xc0cb0410,0xbad03e7c,0xb504f333,
        0xaf67a93b,0xa9f6f34c,0xa4b16f74,0x9f95c6b9,
        0x9aa2acc6,0x95d6df94,0x91312718,0x8cb054f6,
        0x88534433,0x8418d8e8,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  992, 1953, 2884, 3786, 4660, 5507, 6328, 7123, 7894, 8641,
         9365,10066,10746,11404,12042,12660,13259,13840,14402,14947,15475,
        15987,
};

#define LOAD_AVG_PERIOD 22
#define LOAD_AVG_MAX 32984
#define LOAD_AVG_MAX_N 237

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_20
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf7479a6d,0xeedb4007,0xe6b859ad,
        0xdedc66d6,0xd744fcc9,0xcfefc5e5,0xc8da80e0,
        0xc203001c,0xbb6728fa,0xb504f333,0xaeda6839,
        0xa8e5a29d,0xa324cd78,0x9d9623df,0x9837f050,
        0x93088c35,0x8e065f59,0x892fdf70,0x84838f9e,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  989, 1944, 2866, 3757, 4618, 5449, 6252, 7028, 7777, 8501,
         9200, 9875,10527,11157,11766,12354,12922,13470,14000,14512,
};

#define LOAD_AVG_PERIOD 20
#define LOAD_AVG_MAX 30032
#define LOAD_AVG_MAX_N 215

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_18
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf6544d25,0xed062008,0xe411f039,
        0xdb745776,0xd32a105b,0xcb2ff529,0xc382fe8e,
        0xbc204284,0xb504f333,0xae2e5de1,0xa799e9eb,
        0xa14517cb,0x9b2d8023,0x9550d2d4,0x8facd61d,
        0x8a3f65c3,0x85067241,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  985, 1933, 2845, 3722, 4566, 5378, 6160, 6912, 7636, 8332,
         9002, 9647,10267,10864,11438,11991,12523,13035,
};

#define LOAD_AVG_PERIOD 18
#define LOAD_AVG_MAX 27081
#define LOAD_AVG_MAX_N 193

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_16
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf5257d14,0xeac0c6e6,0xe0ccdeeb,
        0xd744fcc9,0xce248c14,0xc5672a10,0xbd08a39e,
        0xb504f333,0xad583ee9,0xa5fed6a9,0x9ef5325f,
        0x9837f050,0x91c3d373,0x8b95c1e3,0x85aac367,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  980, 1919, 2818, 3679, 4503, 5292, 6048, 6772, 7465, 8129,
         8764, 9373, 9956,10514,11048,11560,
};

#define LOAD_AVG_PERIOD 16
#define LOAD_AVG_MAX 24130
#define LOAD_AVG_MAX_N 172

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_14
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf3a24b24,0xe7dd818c,0xdcaa4034,
        0xd2017f74,0xc7dc8e94,0xbe350f94,0xb504f333,
        0xac46751e,0xa3f41854,0x9c08a3b0,0x947f1ea5,
        0x8d52ce1f,0x867f318b,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  974, 1901, 2783, 3623, 4422, 5182, 5906, 6595, 7250, 7874,
         8468, 9033, 9571,10083,
};

#define LOAD_AVG_PERIOD 14
#define LOAD_AVG_MAX 21178
#define LOAD_AVG_MAX_N 150

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_12
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xf1a1bf37,0xe411f039,0xd744fcc9,
        0xcb2ff529,0xbfc886ba,0xb504f333,0xaadc0846,
        0xa14517cb,0x9837f050,0x8facd61d,0x879c7c96,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  966, 1878, 2739, 3551, 4318, 5042, 5725, 6370, 6979, 7553,
         8095, 8607,
};

#define LOAD_AVG_PERIOD 12
#define LOAD_AVG_MAX 18227
#define LOAD_AVG_MAX_N 128

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_10
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xeedb4007,0xdedc66d6,0xcfefc5e5,
        0xc203001c,0xb504f333,0xa8e5a29d,0x9d9623df,
        0x93088c35,0x892fdf70,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  955, 1846, 2677, 3453, 4177, 4852, 5482, 6070, 6618, 7130,
};

#define LOAD_AVG_PERIOD 10
#define LOAD_AVG_MAX 15277
#define LOAD_AVG_MAX_N 107

#endif

#ifdef CONFIG_PELT_UTIL_HALFLIFE_8
static const u32 runnable_avg_yN_inv[] __maybe_unused = {
        0xffffffff,0xeac0c6e6,0xd744fcc9,0xc5672a10,
        0xb504f333,0xa5fed6a9,0x9837f050,0x8b95c1e3,
};

static const u32 runnable_avg_yN_sum[] = {
            0,  939, 1800, 2589, 3313, 3977, 4585, 5143, 5655,
};

#define LOAD_AVG_PERIOD 8
#define LOAD_AVG_MAX 12326
#define LOAD_AVG_MAX_N 85

#endif
